name: Build Docker Image

on:
  push:
    paths:
      - build-base.sh
      - .github/workflows/build.yml
  schedule:
    - cron: '5 3 * * *'
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: chainguard-dev/apko
          binaries-location: apko_0.13.2_linux_amd64

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u shyim --password-stdin

      - name: Build base and push
        run: apko publish wolfi-base.yaml ghcr.io/shyim/php-cs-fixer:base
  cs-fixer:
    needs: [base]
    runs-on: ubuntu-latest
    steps:
      - name: Get latest PHP-CS-Fixer version
        id: cs_fixer_version
        run: |
          VERSION=$(curl https://api.github.com/repos/PHP-CS-Fixer/PHP-CS-Fixer/releases/latest | jq '.tag_name | ltrimstr("v")' -r)
          echo "CS_FIXER_VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "CS_FIXER_VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u shyim --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_CS_FIXER_VERSION=${{ steps.cs_fixer_version.outputs.CS_FIXER_VERSION }}
          tags: |
            shyim/php-cs-fixer:latest
            shyim/php-cs-fixer:${{ steps.cs_fixer_version.outputs.CS_FIXER_VERSION }}
            ghcr.io/shyim/php-cs-fixer:latest
            ghcr.io/shyim/php-cs-fixer:${{ steps.cs_fixer_version.outputs.CS_FIXER_VERSION }}

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/shyim/php-cs-fixer
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
